### ISSUE TITLE
想问一下wifi驱动怎么添加

### ISSUE THREAD

**Issue by MCredbear** [Gah0/android_kernel_xiaomi_libra#9]
我从高通的源码站下到了qcacld-2.0的源码，然后照抄你的Kbuild和Makefile配置了编译选项，内核成功编译了，驱动也被编译进去了，但是刷入后还是无法打开wifi

**Comment by Gah0** [comment]
啊，17天之前的问题，我的疏忽。
3fa60e024a2708ccd370fcef463dcfb25ab247c7
0b5d5b390afb6cb3702a9d4aca8b17e52cb5a8d8
cfc8c75d95d3abf6ba0487983330fbacb958f7bc
a408541d626ebee6d07524ae9a32beefca38727a
用上这几个试试吧。
miui系统还要cherry-pick上的[referenced commit](https://github.com/Gah0/android_kernel_xiaomi_libra/commit/437891579389b8ecd629a48af774f3aa13bbcf28)，做成模块才能打开wifi

没有要问的我关闭问题啦~
